name: "Build Change Log"
description: "Build slack message for change log"
outputs:
  text:
    value: ${{ steps.mrkdwn_changelog.outputs.value }}
    description: "slack message for change log"

runs:
  using: "composite"
  steps:
    - name: Update changelog
      id: changelog
      # Cspell:ignore requarks
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        fromTag: ${{ github.sha }}
        toTag: ${{ github.event.before }}
        writeToFile: false
        excludeTypes: ""

    - name: Convert changelog from markdown to slack
      if: ${{ steps.changelog.outputs.changes }}
      id: mrkdwn_changelog
      uses: LoveToKnow/slackify-markdown-action@v1.1.1
      with:
        text: ${{ steps.changelog.outputs.changes }}
