name: Slack Message
on:
  push:
    branches:
      - main
jobs:
  slack:
    name: Slack Message
    runs-on: ubuntu-22.04
    steps:
      # Cspell:ignore benjlevesque
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - id: slack-wip
        name: Send deployed notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            "text": "GitHub Action build result: ${{ job.status }}\n${{github.repository}} ${{steps.short-sha.outputs.sha}}\n${{ inputs.site }}"

      - name: Sleep
        run: sleep 10

      - name: Generate CHANGELOG
        id: changelog
        uses: ./.github/actions/generate-changelog

      - id: slack-deployed
        name: Send deployed notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            thread_ts: "${{ steps.slack-wip.outputs.ts }}"
            "text": "GitHub Action build result: ${{ job.status }}\n${{github.repository}} ${{steps.short-sha.outputs.sha}}\n${{ inputs.site }}"
            "blocks":
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*${{github.repository}}*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{steps.short-sha.outputs.sha}}>"
                  - type: "mrkdwn"
                    text: "*Environment*\n<${{ inputs.url }}|${{ inputs.site }}>"
