name: Slack Message
on:
  push:
    branches:
      - main
jobs:
  slack:
    name: Slack Message
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      # Cspell:ignore benjlevesque
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Generate CHANGELOG
        id: changelog
        uses: ./.github/actions/generate-changelog

      - id: slack-deployed
        name: Send deployed notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*✅ Deployed*"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>*\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ steps.short-sha.outputs.sha }}>"
                  - type: "mrkdwn"
                    text: "*Environment*\n<https://github.com/vp-playground/slack-github-action-v2|vp-playground/slack-github-action-v2>"
              - type: "context"
                elements:
                  - type: "mrkdwn"
                    text: ${{ steps.changelog.outputs.text && toJSON(steps.changelog.outputs.text) || '"_No changes_"'  }}
